name: Changesets
on:
  push:
    branches:
      - main
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get last commit message
        id: get_commit_message
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"
      
      - name: setup node.js
        if: ${{ steps.get_commit_message.outputs.message =~ /Publish version/i }}
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: install pnpm
        if: ${{ steps.get_commit_message.outputs.message =~ /Publish version/i }}
        run: npm i pnpm@latest -g

      - name: install dependencies
        if: ${{ steps.get_commit_message.outputs.message =~ /Publish version/i }}
        run: pnpm install

      - name: npm login
        if: ${{ steps.get_commit_message.outputs.message =~ /Publish version/i }}
        run: pnpm login

      - name: create and publish versions
        if: ${{ steps.get_commit_message.outputs.message =~ /Publish version/i }}
        run: pnpm -r publish --no-git-checks
